import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const UserComponent = () => {
  const { user } = useUser();

  console.log(user);

  if (!user) throw new Error("error");

  return (
    <div>
      <img
        src={user.profileImageUrl}
        alt="Profile Image"
        className="h-20 w-20 rounded-full"
      ></img>
    </div>
  );
};

const RenderComponent = () => {
  const { data } = api.posts.getAll.useQuery();

  console.log(data);

  if (!data) return <div>Loading...</div>;

  return (
    <div className="mt-16 flex">
      <input
        placeholder="Agrega un post"
        className="bg-transparent outline-none"
      />
      <div className="flex flex-col">
        {data?.map(({ post }) => (
          <div key={post.id}>{post.content}</div>
        ))}
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  console.log(process.env.DATABASE_URL);

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-auto mt-20 w-[70%]">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && (
            <div>
              <div className="flex gap-4">
                <UserComponent></UserComponent>
                <SignOutButton />
              </div>
              <RenderComponent></RenderComponent>
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
